export const categoryItems = [
  { label: 'Restaurante', value: 'Restaurante' },
  { label: 'Hotel', value: 'Hotel' },
  { label: 'Pousada', value: 'Pousada' },
  { label: 'Motel', value: 'Motel' },
  { label: 'Hostel', value: 'Hostel' },
  { label: 'Parque', value: 'Parque' },
  { label: 'Praia', value: 'Praia' },
  { label: 'Loja', value: 'Loja' },
  { label: 'Boutique', value: 'Boutique' },
  { label: 'Café', value: 'Café' },
  { label: 'Padaria', value: 'Padaria' },
  { label: 'Pizzaria', value: 'Pizzaria' },
  { label: 'Lanchonete', value: 'Lanchonete' },
  { label: 'Hamburgueria', value: 'Hamburgueria' },
  { label: 'Churrascaria', value: 'Churrascaria' },
  { label: 'Sorveteria', value: 'Sorveteria' },
  { label: 'Açaiteria', value: 'Açaiteria' },
  { label: 'Pastelaria', value: 'Pastelaria' },
  { label: 'Doceria', value: 'Doceria' },
  { label: 'Confeitaria', value: 'Confeitaria' },
  { label: 'Adega', value: 'Adega' },
  { label: 'Bar', value: 'Bar' },
  { label: 'Pub', value: 'Pub' },
  { label: 'Cervejaria', value: 'Cervejaria' },
  { label: 'Cervejaria Artesanal', value: 'Cervejaria Artesanal' },
  { label: 'Casa de Chá', value: 'Casa de Chá' },
  { label: 'Food Truck', value: 'Food Truck' },
  { label: 'Quiosque', value: 'Quiosque' },
  { label: 'Supermercado', value: 'Supermercado' },
  { label: 'Mercado', value: 'Mercado' },
  { label: 'Mini Mercado', value: 'Mini Mercado' },
  { label: 'Hortifruti', value: 'Hortifruti' },
  { label: 'Açougue', value: 'Açougue' },
  { label: 'Peixaria', value: 'Peixaria' },
  { label: 'Feira Livre', value: 'Feira Livre' },
  { label: 'Farmácia', value: 'Farmácia' },
  { label: 'Drogaria', value: 'Drogaria' },
  { label: 'Hospital', value: 'Hospital' },
  { label: 'Clínica Médica', value: 'Clínica Médica' },
  { label: 'Consultório Médico', value: 'Consultório Médico' },
  { label: 'Laboratório', value: 'Laboratório' },
  { label: 'Clínica Odontológica', value: 'Clínica Odontológica' },
  { label: 'Dentista', value: 'Dentista' },
  { label: 'Oftalmologista', value: 'Oftalmologista' },
  { label: 'Fisioterapia', value: 'Fisioterapia' },
  { label: 'Quiropraxia', value: 'Quiropraxia' },
  { label: 'Hospital Veterinário', value: 'Hospital Veterinário' },
  { label: 'Pet Shop', value: 'Pet Shop' },
  { label: 'Clínica Veterinária', value: 'Clínica Veterinária' },
  { label: 'Academia', value: 'Academia' },
  { label: 'Estúdio de Pilates', value: 'Estúdio de Pilates' },
  { label: 'Box de Crossfit', value: 'Box de Crossfit' },
  { label: 'Estúdio de Yoga', value: 'Estúdio de Yoga' },
  { label: 'Spa', value: 'Spa' },
  { label: 'Salão de Beleza', value: 'Salão de Beleza' },
  { label: 'Barbearia', value: 'Barbearia' },
  { label: 'Clínica de Estética', value: 'Clínica de Estética' },
  { label: 'Manicure e Pedicure', value: 'Manicure e Pedicure' },
  { label: 'Centro de Massagem', value: 'Centro de Massagem' },
  { label: 'Estúdio de Tatuagem', value: 'Estúdio de Tatuagem' },
  { label: 'Estúdio de Piercing', value: 'Estúdio de Piercing' },
  { label: 'Shopping Center', value: 'Shopping Center' },
  { label: 'Galeria Comercial', value: 'Galeria Comercial' },
  { label: 'Outlet', value: 'Outlet' },
  { label: 'Loja de Roupas', value: 'Loja de Roupas' },
  { label: 'Loja de Calçados', value: 'Loja de Calçados' },
  { label: 'Loja de Eletrônicos', value: 'Loja de Eletrônicos' },
  { label: 'Loja de Celulares', value: 'Loja de Celulares' },
  { label: 'Loja de Móveis', value: 'Loja de Móveis' },
  { label: 'Loja de Decoração', value: 'Loja de Decoração' },
  { label: 'Loja de Brinquedos', value: 'Loja de Brinquedos' },
  { label: 'Loja de Informática', value: 'Loja de Informática' },
  { label: 'Papelaria', value: 'Papelaria' },
  { label: 'Livraria', value: 'Livraria' },
  { label: 'Banca de Jornal', value: 'Banca de Jornal' },
  { label: 'Autopeças', value: 'Autopeças' },
  { label: 'Oficina Mecânica', value: 'Oficina Mecânica' },
  { label: 'Funilaria e Pintura', value: 'Funilaria e Pintura' },
  { label: 'Borracharia', value: 'Borracharia' },
  { label: 'Auto Elétrica', value: 'Auto Elétrica' },
  { label: 'Posto de Gasolina', value: 'Posto de Gasolina' },
  { label: 'Estacionamento', value: 'Estacionamento' },
  { label: 'Lava Rápido', value: 'Lava Rápido' },
  { label: 'Transportadora', value: 'Transportadora' },
  { label: 'Locadora de Veículos', value: 'Locadora de Veículos' },
  { label: 'Concessionária', value: 'Concessionária' },
  { label: 'Aeroporto', value: 'Aeroporto' },
  { label: 'Rodoviária', value: 'Rodoviária' },
  { label: 'Estação de Trem', value: 'Estação de Trem' },
  { label: 'Estação de Metrô', value: 'Estação de Metrô' },
  { label: 'Ponto de Táxi', value: 'Ponto de Táxi' },
  { label: 'Escola', value: 'Escola' },
  { label: 'Universidade', value: 'Universidade' },
  { label: 'Creche', value: 'Creche' },
  { label: 'Curso de Idiomas', value: 'Curso de Idiomas' },
  { label: 'Autoescola', value: 'Autoescola' },
  { label: 'Biblioteca', value: 'Biblioteca' },
  { label: 'Cinema', value: 'Cinema' },
  { label: 'Teatro', value: 'Teatro' },
  { label: 'Museu', value: 'Museu' },
  { label: 'Centro Cultural', value: 'Centro Cultural' },
  { label: 'Casa de Shows', value: 'Casa de Shows' },
  { label: 'Arena', value: 'Arena' },
  { label: 'Estádio', value: 'Estádio' },
  { label: 'Quadra Esportiva', value: 'Quadra Esportiva' },
  { label: 'Clube', value: 'Clube' },
  { label: 'Piscina Pública', value: 'Piscina Pública' },
  { label: 'Zoológico', value: 'Zoológico' },
  { label: 'Aquário', value: 'Aquário' },
  { label: 'Parque Aquático', value: 'Parque Aquático' },
  { label: 'Camping', value: 'Camping' },
  { label: 'Trilha Ecológica', value: 'Trilha Ecológica' },
  { label: 'Mirante', value: 'Mirante' },
  { label: 'Ponto Turístico', value: 'Ponto Turístico' },
  { label: 'Igreja', value: 'Igreja' },
  { label: 'Templo', value: 'Templo' },
  { label: 'Mesquita', value: 'Mesquita' },
  { label: 'Sinagoga', value: 'Sinagoga' },
  { label: 'Cemitério', value: 'Cemitério' },
  { label: 'Cartório', value: 'Cartório' },
  { label: 'Prefeitura', value: 'Prefeitura' },
  { label: 'Correios', value: 'Correios' },
  { label: 'Banco', value: 'Banco' },
  { label: 'Lotérica', value: 'Lotérica' },
  { label: 'Agência de Viagens', value: 'Agência de Viagens' },
  { label: 'Imobiliária', value: 'Imobiliária' },
  { label: 'Escritório de Advocacia', value: 'Escritório de Advocacia' },
  { label: 'Contabilidade', value: 'Contabilidade' },
  { label: 'Coworking', value: 'Coworking' },
  { label: 'Sebo', value: 'Sebo' },
  { label: 'Brechó', value: 'Brechó' },
  { label: 'Aluguel de Roupas', value: 'Aluguel de Roupas' },
  { label: 'Costureira', value: 'Costureira' },
  { label: 'Ateliê', value: 'Ateliê' },
  { label: 'Marcenaria', value: 'Marcenaria' },
  { label: 'Serralheria', value: 'Serralheria' },
  { label: 'Vidraçaria', value: 'Vidraçaria' },
  { label: 'Pinturas e Reformas', value: 'Pinturas e Reformas' },
  { label: 'Construtora', value: 'Construtora' },
  { label: 'Imobiliária', value: 'Imobiliária' },
  { label: 'Materiais de Construção', value: 'Materiais de Construção' },
  { label: 'Depósito de Gás', value: 'Depósito de Gás' },
  { label: 'Serralheria', value: 'Serralheria' },
  { label: 'Oficina de Bicicleta', value: 'Oficina de Bicicleta' },
  { label: 'Assistência Técnica', value: 'Assistência Técnica' },
  { label: 'Eletricista', value: 'Eletricista' },
  { label: 'Encanador', value: 'Encanador' },
  { label: 'Jardinagem', value: 'Jardinagem' },
  { label: 'Floricultura', value: 'Floricultura' },
  { label: 'Papelaria', value: 'Papelaria' },
  { label: 'Fotografia', value: 'Fotografia' },
  { label: 'Estúdio Fotográfico', value: 'Estúdio Fotográfico' },
  { label: 'Loja de Instrumentos Musicais', value: 'Loja de Instrumentos Musicais' },
  { label: 'Loja de Bicicletas', value: 'Loja de Bicicletas' },
  { label: 'Loja de Esportes', value: 'Loja de Esportes' },
  { label: 'Loja de Games', value: 'Loja de Games' },
  { label: 'Lan House', value: 'Lan House' },
  { label: 'Loja de Informática', value: 'Loja de Informática' },
  { label: 'Ponto Turístico', value: 'Ponto Turístico' },
  { label: 'Casa de Eventos', value: 'Casa de Eventos' },
  { label: 'Buffet', value: 'Buffet' },
  { label: 'Salão de Festas', value: 'Salão de Festas' },
  { label: 'Loja de Presentes', value: 'Loja de Presentes' },
  { label: 'Papelaria', value: 'Papelaria' },
  { label: 'Relógioaria', value: 'Relógioaria' },
  { label: 'Joalheria', value: 'Joalheria' },
  { label: 'Ótica', value: 'Ótica' },
  { label: 'Loja de Cosméticos', value: 'Loja de Cosméticos' },
  { label: 'Perfumaria', value: 'Perfumaria' },
  { label: 'Loja de Utilidades', value: 'Loja de Utilidades' },
  { label: 'Casa de Ferragens', value: 'Casa de Ferragens' },
  { label: 'Depósito de Bebidas', value: 'Depósito de Bebidas' },
  { label: 'Empório', value: 'Empório' },
  { label: 'Mercadinho', value: 'Mercadinho' },
  { label: 'Distribuidora de Água', value: 'Distribuidora de Água' },
  { label: 'Lavanderia', value: 'Lavanderia' },
  { label: 'Costureira', value: 'Costureira' },
  { label: 'Refrigeração', value: 'Refrigeração' },
  { label: 'Locadora de Equipamentos', value: 'Locadora de Equipamentos' },
  { label: 'Serralheria', value: 'Serralheria' },
  { label: 'Pinturas e Reformas', value: 'Pinturas e Reformas' },
  { label: 'Seguradora', value: 'Seguradora' },
  { label: 'Corretores de Imóveis', value: 'Corretores de Imóveis' },
  { label: 'Agência de Turismo', value: 'Agência de Turismo' },
  { label: 'Casa Lotérica', value: 'Casa Lotérica' },
  { label: 'Sindicato', value: 'Sindicato' },
  { label: 'Associação', value: 'Associação' },
  { label: 'Centro Comunitário', value: 'Centro Comunitário' },
  { label: 'Centro de Atendimento', value: 'Centro de Atendimento' },
  { label: 'Procon', value: 'Procon' },
  { label: 'Detran', value: 'Detran' },
  { label: 'Delegacia', value: 'Delegacia' },
  { label: 'Corpo de Bombeiros', value: 'Corpo de Bombeiros' },
  { label: 'Polícia Militar', value: 'Polícia Militar' },
  { label: 'Polícia Civil', value: 'Polícia Civil' },
  { label: 'Guarda Municipal', value: 'Guarda Municipal' },
];
