export const categoryItems = [
  { label: 'Restaurante', value: 'restaurante' },
  { label: 'Hotel', value: 'hotel' },
  { label: 'Parque', value: 'parque' },
  { label: 'Loja', value: 'loja' },
  { label: 'Café', value: 'cafe' },
  { label: 'Pizzaria', value: 'pizzaria' },
  { label: 'Bar', value: 'bar' },
  { label: 'Museu', value: 'museu' },
  { label: 'Cinema', value: 'cinema' },
  { label: 'Teatro', value: 'teatro' },
  { label: 'Academia', value: 'academia' },
  { label: 'Spa', value: 'spa' },
  { label: 'Farmácia', value: 'farmacia' },
  { label: 'Supermercado', value: 'supermercado' },
  { label: 'Livraria', value: 'livraria' },
  { label: 'Clínica Médica', value: 'clinica_medica' },
  { label: 'Dentista', value: 'dentista' },
  { label: 'Hospital', value: 'hospital' },
  { label: 'Escola', value: 'escola' },
  { label: 'Universidade', value: 'universidade' },
  { label: 'Banco', value: 'banco' },
  { label: 'Oficina Mecânica', value: 'oficina_mecanica' },
  { label: 'Posto de Gasolina', value: 'gasolina' },
  { label: 'Sorveteria', value: 'sorveteria' },
  { label: 'Padaria', value: 'padaria' },
  { label: 'Hamburgueria', value: 'hamburgueria' },
  { label: 'Churrascaria', value: 'churrascaria' },
  { label: 'Comida Japonesa', value: 'comida_japonesa' },
  { label: 'Comida Chinesa', value: 'comida_chinesa' },
  { label: 'Comida Italiana', value: 'comida_italiana' },
  { label: 'Comida Mexicana', value: 'comida_mexicana' },
  { label: 'Comida Vegana', value: 'comida_vegana' },
  { label: 'Comida Vegetariana', value: 'comida_vegetariana' },
  { label: 'Frutos do Mar', value: 'frutos_do_mar' },
  { label: 'Fast Food', value: 'fast_food' },
  { label: 'Food Truck', value: 'food_truck' },
  { label: 'Lanchonete', value: 'lanchonete' },
  { label: 'Pastelaria', value: 'pastelaria' },
  { label: 'Açaiteria', value: 'acaiteria' },
  { label: 'Doceria', value: 'doceria' },
  { label: 'Confeitaria', value: 'confeitaria' },
  { label: 'Adega', value: 'adega' },
  { label: 'Cervejaria Artesanal', value: 'cervejaria_artesanal' },
  { label: 'Casa de Chá', value: 'casa_de_cha' },
  { label: 'Quiosque', value: 'quiosque' },
  { label: 'Shopping Center', value: 'shopping_center' },
  { label: 'Mercado', value: 'mercado' },
  { label: 'Aeroporto', value: 'aeroporto' },
];